// <auto-generated />
using System;
using BlogApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogApp.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20241225140202_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogApp.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HeaderImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Admin",
                            Content = "I just realized I haven't written about the AHA Stack on the blog...",
                            CreatedDate = new DateTime(2024, 12, 20, 17, 2, 2, 355, DateTimeKind.Local).AddTicks(3987),
                            HeaderImage = "https://astro.build/assets/press/logomark-light.svg",
                            Summary = "Understanding the AHA Stack - Astro, HTMX, and Alpine.js",
                            Tags = "[\"astro\",\"htmx\",\"alpine\",\"javascript\",\"web-development\"]",
                            Title = "The AHA Stack"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Admin",
                            Content = "The useOptimistic hook is a powerful feature in React...",
                            CreatedDate = new DateTime(2024, 12, 21, 17, 2, 2, 357, DateTimeKind.Local).AddTicks(525),
                            HeaderImage = "https://reactjs.org/logo-og.png",
                            Summary = "Learn about optimistic updates in React",
                            Tags = "[\"react\",\"hooks\",\"javascript\",\"optimization\"]",
                            Title = "The useOptimistic hook"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
